blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/jimstratus/ICS-ext-forcesensitivity/tree/main/docs
    about: Check the documentation before opening an issue
  - name: Discussions
    url: https://github.com/jimstratus/ICS-ext-forcesensitivity/discussions
    about: Ask questions and discuss features
